# Generated by Django 5.2.12 on 2026-05-10 09:44

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='answerlike',
            trigger=pgtrigger.compiler.Trigger(name='update_rating_on_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='UPDATE questions_answer SET rating = rating + NEW.value WHERE id = NEW.answer_id; RETURN NEW;', hash='54b87e12e184b16d59031e01371a10a13eae0945', operation='INSERT', pgid='pgtrigger_update_rating_on_insert_21851', table='questions_answerlike', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='answerlike',
            trigger=pgtrigger.compiler.Trigger(name='update_rating_on_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.value IS DISTINCT FROM NEW.value)', func='UPDATE questions_answer SET rating = rating - OLD.value + NEW.value WHERE id = NEW.answer_id; RETURN NEW;', hash='0186aec8a755e0b43c759050f6ac9c05fabf081c', operation='UPDATE', pgid='pgtrigger_update_rating_on_update_c54c6', table='questions_answerlike', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='answerlike',
            trigger=pgtrigger.compiler.Trigger(name='update_rating_on_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='UPDATE questions_answer SET rating = rating - OLD.value WHERE id = OLD.answer_id; RETURN OLD;', hash='952c3329d414e25a3ec0f963d59838028c066a00', operation='DELETE', pgid='pgtrigger_update_rating_on_delete_03a20', table='questions_answerlike', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionlike',
            trigger=pgtrigger.compiler.Trigger(name='update_rating_on_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='UPDATE questions_question SET rating = rating + NEW.value WHERE id = NEW.question_id; RETURN NEW;', hash='dc62993bb79ed8c096faaaeaa73e4d20b47aa099', operation='INSERT', pgid='pgtrigger_update_rating_on_insert_bd732', table='questions_questionlike', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionlike',
            trigger=pgtrigger.compiler.Trigger(name='update_rating_on_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.value IS DISTINCT FROM NEW.value)', func='UPDATE questions_question SET rating = rating - OLD.value + NEW.value WHERE id = NEW.question_id; RETURN NEW;', hash='cd75f8098537db09d109bb1bbae2798894cd6a16', operation='UPDATE', pgid='pgtrigger_update_rating_on_update_9dfcf', table='questions_questionlike', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='questionlike',
            trigger=pgtrigger.compiler.Trigger(name='update_rating_on_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='UPDATE questions_question SET rating = rating - OLD.value WHERE id = OLD.question_id; RETURN OLD;', hash='265d8c7d5159c8f14775db3cacf9f701550ada73', operation='DELETE', pgid='pgtrigger_update_rating_on_delete_e0066', table='questions_questionlike', when='AFTER')),
        ),
    ]
